# version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - appnetwork
  pgadmin:
    image: dpage/pgadmin4
    container_name: local_pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - local_pgadmindata:/var/lib/pgadmin
    networks:
      - appnetwork

volumes:
  local_pgdata:
    name: local_pgdata_volume
  local_pgadmindata:
    name: local_pgadmindata_volume
networks:
  appnetwork:
    name: myappnetwork