version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - local_elasticsearch_volume:/usr/share/elasticsearch/data/
      - ./elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elk-backup:/usr/share/elasticsearch/snapshots
    environment:
      discovery.type: single-node
      http.host: 0.0.0.0
      transport.host: 0.0.0.0
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      cluster.name: elasticsearch
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: ${HEAP_SIZE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - local_elk_network
    restart: unless-stopped

  logstash:
    image: logstash:${STACK_VERSION}
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - local_logstash_volume:/usr/share/logstash/data
      - /home/shourov/Desktop/logs/:/logs/
    depends_on:
      - elasticsearch
    networks:
      - local_elk_network
    restart: unless-stopped
    profiles:
      - data_transform
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: kibana:${STACK_VERSION}
    ports:
      - "5601:5601"
    volumes:
      - ./elk-config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - local_kibana_volume:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - local_elk_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  local_elk_network:
    driver: bridge
    name: local_elk_network

volumes:
  local_elasticsearch_volume:
    name: local_elasticsearch_volume
  local_logstash_volume:
    name: local_logstash_volume
  local_kibana_volume:
    name: local_kibana_volume
