services:
  zookeeper:
    image: zookeeper:3.6.2
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/logs:/datalog
    restart: always

  kafka:
    image: wurstmeister/kafka:2.13-2.7.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - ./kafka/data:/var/lib/kafka/data
      - ./kafka/logs:/var/lib/kafka/logs
    restart: always

  Kafka-Ui:
    depends_on:
      - kafka
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
     - "8080:8080"
    environment:
     KAFKA_BROKERS: "kafka:9092"
    restart: always