# https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee
# version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: local_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - local_mysqldata:/var/lib/mysql
    networks:
      - appnetwork
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  local_mysqldata:
    name: local_mysqldata_volume
networks:
  appnetwork:
    name: myappnetwork
    external: true
